import os
import json
import uuid
import boto3
from io import BytesIO
from datetime import datetime, timezone
from botocore.config import Config
from botocore.exceptions import ClientError
from reportlab.pdfgen import canvas  # make sure reportlab is included in your Lambda package/layer

PACKETS_BUCKET = os.environ.get("PACKETS_BUCKET", "")
PACKETS_PREFIX = os.environ.get("PACKETS_PREFIX", "packets/")
URL_EXPIRES_SECONDS = int(os.environ.get("URL_EXPIRES_SECONDS", "300"))


def _resp(status_code: int, body, content_type: str = "application/json"):
    """
    API Gateway expects `body` to be a string.
    """
    if body is None:
        body = ""
    if not isinstance(body, str):
        body = json.dumps(body)

    return {
        "statusCode": status_code,
        "headers": {
            "Content-Type": content_type,
            # Helpful defaults
            "Cache-Control": "no-store",
        },
        "body": body,
    }


def _detect_bucket_region(bucket: str) -> str:
    """
    Avoid region/signing mismatches by asking S3 what region the bucket is in.
    Requires s3:GetBucketLocation permission.
    """
    try:
        s3 = boto3.client(
            "s3",
            region_name="us-east-1",
            config=Config(signature_version="s3v4"),
        )
        loc = s3.get_bucket_location(Bucket=bucket).get("LocationConstraint")
        return loc or "us-east-1"  # None/"" means us-east-1
    except ClientError:
        return os.environ.get("AWS_REGION") or os.environ.get("AWS_DEFAULT_REGION") or "us-east-1"


def _parse_payload(event) -> dict:
    """
    Supports both:
    - Direct Lambda invoke tests where event is already a dict payload
    - API Gateway HTTP API where JSON is usually in event["body"] (string)
    """
    if not isinstance(event, dict):
        return {}

    # API Gateway HTTP API / Lambda proxy: body is a string
    if "body" in event and event["body"] is not None:
        body = event["body"]
        if isinstance(body, str) and body.strip():
            try:
                return json.loads(body)
            except Exception:
                return {}

        # Sometimes tests pass a dict body
        if isinstance(body, dict):
            return body

    # Direct invoke style
    return event


def _build_pdf_bytes(run_id: str) -> bytes:
    """
    Generates a valid PDF using ReportLab.
    """
    buf = BytesIO()
    c = canvas.Canvas(buf)
    c.setTitle("CommonMASS Packet")

    c.setFont("Helvetica-Bold", 16)
    c.drawString(72, 750, "CommonMASS Packet (placeholder)")

    c.setFont("Helvetica", 12)
    c.drawString(72, 725, "This is a placeholder PDF generated by AWS Lambda.")
    c.drawString(72, 705, f"Run ID: {run_id}")
    c.drawString(72, 685, f"Generated (UTC): {datetime.now(timezone.utc).isoformat()}")

    c.showPage()
    c.save()

    return buf.getvalue()


def lambda_handler(event, context):
    if not PACKETS_BUCKET:
        return _resp(500, {"error": "PACKETS_BUCKET env var not set"})

    payload = _parse_payload(event)
    return_plain_url = payload.get("return_plain_url") is True

    region = _detect_bucket_region(PACKETS_BUCKET)

    s3 = boto3.client(
        "s3",
        region_name=region,
        config=Config(
            signature_version="s3v4",
            retries={"max_attempts": 2},
        ),
    )

    run_id = str(uuid.uuid4())
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    key = f"{PACKETS_PREFIX}{ts}-{run_id}.pdf"

    # Build a real, valid PDF (fixes “Failed to load PDF document”)
    pdf_bytes = _build_pdf_bytes(run_id)

    try:
        s3.put_object(
            Bucket=PACKETS_BUCKET,
            Key=key,
            Body=pdf_bytes,
            ContentType="application/pdf",
            CacheControl="no-store",
            # Optional: force download instead of inline viewing
            # ContentDisposition='attachment; filename="commonmass-packet.pdf"',
        )
    except ClientError as e:
        return _resp(500, {"error": "Failed to write PDF to S3", "details": str(e)})

    presigned_url = s3.generate_presigned_url(
        "get_object",
        Params={"Bucket": PACKETS_BUCKET, "Key": key},
        ExpiresIn=URL_EXPIRES_SECONDS,
    )

    # If you want plain text response (mostly useful for CLI tests)
    if return_plain_url:
        return _resp(200, presigned_url, content_type="text/plain")

    # Normal JSON response for your React frontend
    return _resp(
        200,
        {
            "run_id": run_id,
            "s3_key": key,
            "expires_in": URL_EXPIRES_SECONDS,
            "bucket_region_used": region,
            "download_url": presigned_url,
        },
        content_type="application/json",
    )